import streamlit as st
import pandas as pd
import joblib


# Page configuration
st.set_page_config(
    page_title="House Price Prediction",
    page_icon="🏠",
    layout="centered"
)


# Load model
model = joblib.load("house_price_model.pkl")


# Title
st.title("🏠 House Price Prediction")

st.write(
    "Enter property details to predict the estimated house price."
)


# Property details
st.header("Property Details")


bhk = st.number_input(
    "Number of BHK",
    min_value=1,
    max_value=10,
    value=2,
    step=1
)


propertytype = st.selectbox(
    "Property Type",
    [
        "Flat",
        "House",
        "Villa"
    ]
)


location = st.text_input(
    "Location",
    value="Ahmedabad"
)


sqft = st.number_input(
    "Area (Square Feet)",
    min_value=100.0,
    max_value=20000.0,
    value=1000.0,
    step=50.0
)


pricepersqft = st.number_input(
    "Price Per Square Feet",
    min_value=100.0,
    max_value=1000000.0,
    value=5000.0,
    step=100.0
)


# Prediction button
if st.button("🔮 Predict House Price"):

    # Create input dataframe
    input_data = pd.DataFrame({
        "bhk": [bhk],
        "propertytype": [propertytype],
        "location": [location],
        "sqft": [sqft],
        "pricepersqft": [pricepersqft]
    })


    # Prediction
    prediction = model.predict(input_data)[0]

    # Avoid negative price
    prediction = max(0, prediction)


    # Input summary
    st.subheader("📋 Input Summary")

    st.write(f"**BHK:** {bhk}")
    st.write(f"**Property Type:** {propertytype}")
    st.write(f"**Location:** {location}")
    st.write(f"**Area:** {sqft:,.0f} sq.ft")
    st.write(f"**Price Per Sq.Ft:** ₹{pricepersqft:,.0f}")


    # Result
    st.success("Prediction completed successfully!")

    st.subheader("💰 Predicted House Price")

    st.metric(
        "Estimated Price",
        f"₹ {prediction:,.2f}"
    )


    # Convert price
    price_lakh = prediction / 100000
    price_crore = prediction / 10000000

    st.write(
        f"**Price in Lakhs:** ₹{price_lakh:,.2f} Lakh"
    )

    st.write(
        f"**Price in Crores:** ₹{price_crore:,.2f} Crore"
    )

    st.info(
        "This is an estimated price generated by the "
        "Machine Learning model."
    )